### User Registration
POST http://localhost:8080/api/users/registration
Content-Type: application/json

{
  "name": "Hong Gil Dong",
  "phone": "010-1234-5678",
  "email": "honggile@sparta.kr",
  "password": "Password123!",
  "gender": "MALE"
}

### User Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "email": "honggile@sparta.kr",
    "password": "Password123!"
}

### User Status
GET http://localhost:8080/api/users/status
Content-Type: application/json

### Product Registration
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "categoryId": 1,
  "name": "New Product",
  "description": "This is a new product description.",
  "price": 29900,
  "stock": 100
}

### Get Products (to find ID)
GET http://localhost:8080/api/products?page=0&size=10
Content-Type: application/json

### Add Item to Cart
POST http://localhost:8080/api/carts
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2
}

### Get Cart List
GET http://localhost:8080/api/carts
Content-Type: application/json

### Update Cart Item Quantity
PATCH http://localhost:8080/api/carts/1
Content-Type: application/json

{
  "quantity": 5
}

### Delete Cart Item
DELETE http://localhost:8080/api/carts/1
Content-Type: application/json

### User Logout
GET http://localhost:8080/api/users/logout
Content-Type: application/json
