version: '3.8'

services:
  elasticsearch:
    container_name: study_elasticsearch
    build:
      context: ./elasticsearch/
      dockerfile: Dockerfile
    environment:
      - node.name=study_elasticsearch
      - discovery.type=single-node  # 클러스터 없이 혼자 실행
      - xpack.security.enabled=false # 로그인 보안 기능 끄기
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # 힙 메모리 크기
    # 메모리 스왑 방지
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" # HTTP 통신 포트
      - "9300:9300" # 노드 간 통신 포트
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      # 데이터 폴더 마운트
      - ./elasticsearch/data:/var/lib/elasticsearch/data
    networks:
      - elk

  logstash:
    container_name: study_logstash
    build:
      context: ./logstash/
      dockerfile: Dockerfile
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - "5001:5001/tcp" # TCP 로그 수집 포트
      - "5001:5001/udp" # UDP 로그 수집 포트
      - "9600:9600"     # 모니터링 포트
    volumes:
      # 설정 파일 마운트
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      # 파이프라인(input/output 설정) 마운트
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      # 스프링 부트 로그 파일 연결
      # 내 컴퓨터의 logs 폴더를 컨테이너의 /log 폴더로 연결
      - type: bind
        source: ./spring-java-03/logs
        target: /log
        read_only: true
    depends_on:
      - elasticsearch # ES가 실행 명령을 받은 뒤에 시작함
    networks:
      - elk

  kibana:
    container_name: study_kibana
    build:
      context: ./kibana/
      dockerfile: Dockerfile
    ports:
      - "5601:5601" # 웹 브라우저 접속 포트
    volumes:
      # 설정 파일 마운트
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge