input {
  file {
    path => "/log/*.log"
    start_position => "end"
    mode => "tail"
    codec => json {
      charset => "UTF-8"
    }
    discover_interval => 5
    stat_interval => 1
    close_older => 0
    sincedb_path => "/dev/null"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "service-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}